site_name: Факультет финансовой экономики МГИМО-Одинцово
site_description: Официальный сайт факультета финансовой экономики МГИМО-Одинцово
docs_dir: docs
site_dir: site

nav:
  - О факультете:
    - Анонсы: index.md
    - День открытых дверей: dod/index.md
    - Интервью декана: interview.md 
    - Рассказывают студенты: dod/students.md
    #- Летняя школа: summer.md
    #- Логотип: logo.md - finec.mgimo.ru/logo / update.md
    - Наш кампус: campus.md
    - Свяжитесь с нами: contacts.md

  - Программы обучения:
    - Обзор программ: program/about.md
    - Экономика:  program/economics.md
    - Менеджмент: program/management.md
    - Бизнес-информатика: program/bi.md

  # Добавить по мере постуления:

  #  - Финансовая экономика и финансовые технологии: program/fefm.md
  #  - Финансовый менеджмент: program/fm.md
  #  - Информационные технологии в международном бизнесе: program/itmb.md

  # Добавить по мере постуления:

  #- Кафедры:
  #  - Кафедра экономики и финансов: chair/finec.md
  #  - Кафедра менеджмента: chair/management.md
  #  - Кафедра математических методов и бизнес-информатики: chair/mmbi.md
  #  - Кафедра цифровой экономики и искусственного интеллекта группы компаний АДВ: chair/ai.md
  
  - Сотрудники:
    - Руководство: people/principals.md
    - Деканат: people/office.md
    - Кафедры: people/departments.md
  
  - Свяжитесь с нами:
    - Контакты: contacts.md

#repo_name: finec-mgimo
#repo_url: https://github.com/epogrebnyak/finec
#edit_uri: '/epogrebnyak/finec/edit/master/source/'

# Copyright
copyright: Copyright &copy; 2020 Факультет финансовой экономики МГИМО-Одинцово

# Custom settings:
extra_css:
  - css/extra.css

# Configuration
theme:
  name: material

  # Custom settings:
  # https://squidfunk.github.io/mkdocs-material/customization/#setup-and-theme-structure
  custom_dir: custom-theme
  
  # https://squidfunk.github.io/mkdocs-material/getting-started/#logo
  logo: img/logo/vector.svg

  # https://squidfunk.github.io/mkdocs-material/getting-started/#favicon
  # The favicon is from mgimo.ru webpage
  favicon: img/logo/favicon-32x32.png

  language: ru

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  features:
    - tabs
    #- instant
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono


# Plugins
plugins:
  - search
  - minify:
      minify_html: true

# # Customization
# extra:
#   social:
#     - icon: fontawesome/brands/github
#       link: https://github.com/squidfunk
#     - icon: fontawesome/brands/gitter
#       link: https://gitter.im/squidfunk/mkdocs-material
#     - icon: fontawesome/brands/docker
#       link: https://hub.docker.com/r/squidfunk/mkdocs-material/
#     - icon: fontawesome/brands/twitter
#       link: https://twitter.com/squidfunk
#     - icon: fontawesome/brands/linkedin
#       link: https://linkedin.com/in/squidfunk/
#     - icon: fontawesome/brands/instagram
#       link: https://instagram.com/squidfunk

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
       linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

google_analytics: ['UA-168750267-1', 'finec.mgimo.ru']